### ISSUE TITLE
[QUESTION] Portability

### ISSUE THREAD

**Issue by calmsacibis995** [xrarch/mintia2#1]
Can MINTIA be ported to other systems? For example, x86 or ARM? Also, can it be re-written in C or C++?

**Comment by hyenasky** [comment]
I'll answer both questions.

1. Can it be ported to other systems?

MINTIA is portable, as seen by the fact that it runs on not one but two fake computers, XR/station and [fox32](https://github.com/fox32-arch). An amd64 port is planned after the base system is done for the rewrite (which is this repository).

This is lengthy but to be comprehensive for posterity's sake, architectural requirements for a MINTIA port include:
- A paging MMU with a page table scheme that supports recursively mapping the page tables, which requires the upper level table entries to have the same format as lower level table entries, and the page tables of all levels to be the same size. This describes all modern general purpose architectures, I think. (May also not have any internal support for a page table hierarchy at all, as long as it is flexible enough to implement a suitable one myself, as seen in MIPS and my own XR17032.)
- All instructions have to be fully abortable upon page fault; the architecture must allow handling page faults by mapping in a page and returning.
- Native word width must be either 32 or 64 bits. Virtual address width must be less or equal to the native word size. Must have atomic 8, 16, 32 bit, and pointer-width store instructions (i.e. no compile-time synthesis from read-modify-write sequences of larger stores is permitted, or several places in the kernel may break).
- If the architecture is used in a platform that supports SMP, it must have suitable multiprocessor atomics such as LL/SC or CAS. Those atomics have to be able to operate on 32-bit data, as well as whatever the pointer size is.
- Little-endian. Probably possible to do a big-endian port but I don't feel like bothering.

And platform requirements include:
- Some form of interval timer interrupt.
- Some form of block-oriented mass storage with a sector size no larger than the architectural page size.
- Preferably, interrupt-driven IO, but can make do without as long as there's a periodic interrupt of some type (like fox32's vblank interrupt).

2. Can it be re-written in C or C++?

There's no reason why not, but it won't be, at least not by me. Half the fun is figuring out whether the bugs are in my compiler or in my kernel, or in my or @ry755's emulators. Plus it's just cool to have a totally NIH'd and self-hosted language ecosystem. I intend to self-host MINTIA on all supported platforms, including the fantasy computers. The amd64 port will involve retargeting the toolchain.
